# config.yaml

setup_extraction:

  variable:
    var_name: ""
    field: ""
    deph_val: -10
    tol: 0.5

  dir_paths:
    dir_input_mooring_nc: "../datasets/mooring-nc"
    dir_output_mooring_csv: "../datasets/mooring-csv"
    dir_input_sat_csv: "../datasets/satellite-csv"


spatio_temp_matching:

  variable:
    cross_radius:
    cross_time:

  dir_paths:
    dir_input_mooring_csv: "../datasets/mooring-csv"
    dir_inout_satellite_csv: "../datasets/satellite-csv"
