# config.yaml

extraction:
  var_name: "VAVH" # VAVH or WSPD
  field: "wave" # wave or wind
  deph_val: 0  # depth value in meter: 0 for wave, -10 for wind

dir_paths:
  dir_input_mooring_nc: C:\Users\eduar\Desktop\materiale Tesi\moorings-nc
  dir_output_mooring_csv: C:\Users\eduar\Desktop\materiale Tesi\moorings-csv
  dir_input_sat_csv: C:\Users\eduar\Desktop\materiale Tesi\satellite-csv
  path_sat_singleFile: C:\Users\eduar\Desktop\materiale Tesi\satellite-csv\ds_S6A_wave.csv

crossMatching:
  cross_radius: 50 # km
  cross_time_val: 1
  cross_time_unit: 'h' # m / h / s
  var_name: "VAVH" # VAVH or WSPD


