# config.yaml
data_extraction:
  variable:
    var_name: "VAVH"
    field: "wave"
    depth_val: 0  # value expressed in meters
  dir_paths:
    dir_input_mooring_nc: ../data/example/moorings_nc
    dir_output_mooring_csv: ../data/example/moorings_csv
    dir_input_sat_csv: ../data/example/satellite_csv
# ---------------------------------------------------------------------
spatio_temp_matching:
  variable:
    var_name: "VAVH"
    cross_radius: 50
    cross_time_val: 15
    cross_time_unit: 'm' # m / h / s
  dir_paths:
    dir_output_mooring_csv: ../data/example/moorings_csv
    dir_input_sat_csv: ../data/example/satellite_csv


